# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Marketplace build

on:
  push:
    branches: [ marketplace ]
  pull_request:
    branches: [ marketplace ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build api
      run: ./mvnw --batch-mode clean install -Padoptium

    - name: Build app
      run: |
        cd marketplace/
        ../mvnw --batch-mode clean install

    - name: Upload yaml schema
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: schema.yaml
        path: marketplace/adoptium-marketplace-schema/target/generated/openapi.yaml

    - name: Upload json schema
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: schema.json
        path: marketplace/adoptium-marketplace-schema/target/generated/openapi.json

    - name: Upload example data
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: example.json
        path: marketplace/adoptium-marketplace-schema-tests/src/test/resources/net/adoptium/marketplace/schema/example.json
